- name: Global OSX settings
  command: defaults write -g {{ item }}
  with_items:
    - AppleShowAllExtensions -bool true
    - com.apple.swipescrolldirection -bool false  # "normal" scrolling
    - AppleKeyboardUIMode -int 3  # tab goes through all controls on dialogs
    - NSNavPanelExpandedStateForSaveMode -boolean true  # save panel expanded
    # - com.apple.keyboard.fnState -int 1  # need to hold fn to get at special keys

- name: Dock settings
  command: defaults write com.apple.dock {{ item }}
  with_items:
    - autohide-time-modifier -int 1
    - tilesize -int 48
    - persistent-apps -array ""
    - expose-animation-duration -float 0.1 
  notify: kill dock


- name: Finder settings
  command: defaults write com.apple.finder {{ item }}
  with_items:
    - NewWindowTarget -string "PfHm"  # Home folder
    - FXEnableSlowAnimation -boolean false # Disable slow animations on shift
    - QLHidePanelOnDeactivate -boolean true  # quicklook hide on defocus
    - _FXShowPosixPathInTitle -bool YES  # Full path
  notify: kill finder

- name: Terminal theme
  command: open ~/Projects/mac-ansible/roles/michal_mac/files/Michal.terminal

- name: Terminal settings
  command: defaults write com.apple.terminal {{ item }}
  with_items:
    - '"Default Window Settings" -string "Michal"'
    - '"Startup Window Settings" -string "Michal"'

- command: chflags nohidden ~/Library/
